### PR TITLE
Batch exception fix when unwrapping exception

### LINKED ISSUE #590: Batch: CompletionException can not be unpacked
I have a batch resolver that throws an exception. The response then contains for every entry the same error (which is okay), but it's only a `java.util.concurrent.CompletionException` with error code `completion`, but I need access to the exception that caused the failure. It doesn't help to add the `CompletionException` to the `smallrye.graphql.unwrapExceptions` config.

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #590 

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by phillip-kruger** [comment]
@t1 - added a test and now also a fix ! I'll do a back port for 1.0.x

**Comment by phillip-kruger** [comment]
@t1 this PR is waiting for you .... please review :)

File: server/implementation/src/main/java/io/smallrye/graphql/execution/datafetcher/AbstractDataFetcher.java [hunk 1]
```diff
@@ -48,10 +43,6 @@ public AbstractDataFetcher(Operation operation, Config config) {
         this.argumentHelper = new ArgumentHelper(operation.getArguments());
         this.partialResultHelper = new PartialResultHelper();
         this.batchLoaderHelper = new BatchLoaderHelper();
-        if (config != null && config.getUnwrapExceptions().isPresent()) {
```
Comment (t1) [inline server/implementation/src/main/java/io/smallrye/graphql/execution/datafetcher/AbstractDataFetcher.java:51]: I would do this with an `ifPresent` block, but that's just a matter of taste, I guess.

File: server/implementation/src/main/java/io/smallrye/graphql/execution/error/ExceptionHandler.java [hunk 2]
```diff
@@ -19,15 +24,21 @@
...
     private final ExceptionLists exceptionLists;
+    protected List<String> unwrapExceptions = new ArrayList<>();
 
     public ExceptionHandler(Config config) {
         this.config = config;
         this.exceptionLists = new ExceptionLists(config.getHideErrorMessageList(), config.getShowErrorMessageList());
+        if (config.getUnwrapExceptions().isPresent()) {
+            this.unwrapExceptions.addAll(config.getUnwrapExceptions().get());
+        }
+        this.unwrapExceptions.addAll(DEFAULT_EXCEPTION_UNWRAP);
```
Comment (t1) [inline server/implementation/src/main/java/io/smallrye/graphql/execution/error/ExceptionHandler.java:35]: Except for the `DataFetcherException`, this (and the constant) is a code duplication with `AbstractDataFetcher`. Maybe it would be better to push that into the `Config` class, so this could would be only `this.unwrapExceptions = config.getAllUnwrapExceptions()`.

File: server/tck/src/test/java/io/smallrye/graphql/test/apps/batch/api/BatchApi.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+        List<BatchPojo> l = new ArrayList<>();
+        l.add(new BatchPojo(1));
+        l.add(new BatchPojo(2));
+        l.add(new BatchPojo(3));
+        l.add(new BatchPojo(4));
+
+        return l;
+    }
+
+    // Nornal Source
```
Comment (t1) [inline server/tck/src/test/java/io/smallrye/graphql/test/apps/batch/api/BatchApi.java:26]:
```suggestion
    // Normal Source
```

**Review by t1 — APPROVED** [review]
With some minor remarks, LGTM, but I don't understand a lot of the context (Uni, etc.)

File: server/implementation/src/main/java/io/smallrye/graphql/execution/error/ExceptionHandler.java (hunk 2 above)
Comment (phillip-kruger) [reply server/implementation/src/main/java/io/smallrye/graphql/execution/error/ExceptionHandler.java:35]: It's been removed (or rather moved) from `AbstractDataFetcher.` So it's not in `AbstractDataFetcher` anymore

File: server/implementation/src/main/java/io/smallrye/graphql/execution/datafetcher/AbstractDataFetcher.java (hunk 1 above)
Comment (phillip-kruger) [reply server/implementation/src/main/java/io/smallrye/graphql/execution/datafetcher/AbstractDataFetcher.java:51]: This is being deleted :)
